# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Importa a biblioteca pandas e matplotlib
import pandas as pd
import matplotlib.pyplot as plt

# Caminho base onde os arquivos CSV estão armazenados no Google Drive
base_path = '/content/drive/MyDrive/PROJETO/'

# Lista contendo os arquivos e seus respectivos anos
arquivos = [
    (f'{base_path}MICRODADOS_ENEM_2019.csv', 2019),
    (f'{base_path}MICRODADOS_ENEM_2020.csv', 2020),
    (f'{base_path}MICRODADOS_ENEM_2021.csv', 2021),
    (f'{base_path}MICRODADOS_ENEM_2022.csv', 2022),
    (f'{base_path}MICRODADOS_ENEM_2023.csv', 2023),
    (f'{base_path}RESULTADOS_2024.csv', 2024)
]

# Percorre todos os arquivos da lista
for arquivo, ano in arquivos:

    try:

        # Lê o arquivo CSV
        df = pd.read_csv(

            # Caminho do arquivo
            arquivo,

            # Separador utilizado no CSV
            sep=';',

            # Codificação dos caracteres
            encoding='latin-1',

            # Lê apenas as colunas necessárias
            usecols=['SG_UF_PROVA', 'NU_NOTA_MT'],

            # Define o tipo da coluna para economizar memória
            dtype={'SG_UF_PROVA': 'category'}
        )

        # Converte a coluna de notas para valores numéricos
        # Valores inválidos serão transformados em NaN
        df['NU_NOTA_MT'] = pd.to_numeric(
            df['NU_NOTA_MT'],
            errors='coerce'
        )

        # Remove linhas com valores nulos
        df = df.dropna()

        # Agrupa os dados por estado
        # Calcula a média das notas de matemática
        # Ordena os valores do menor para o maior
        media_por_estado = (
            df.groupby('SG_UF_PROVA', observed=False)['NU_NOTA_MT']
            .mean()
            .sort_values()
        )

        # Cria um gráfico de barras horizontais
        ax = media_por_estado.plot(
            kind='barh',
            figsize=(10, 6),
            color='skyblue'
        )

        # Define o título do gráfico
        plt.title(f'Média de Matemática por Estado ({ano})')

        # Nome do eixo X
        plt.xlabel('Nota média')

        # Nome do eixo Y
        plt.ylabel('Estado')

        # Adiciona os valores ao lado das barras
        for i, v in enumerate(media_por_estado):

            ax.text(

                # Posição horizontal do texto
                v + 0.5,

                # Posição vertical
                i,

                # Texto formatado com duas casas decimais
                f'{v:.2f}',

                # Alinhamento vertical
                va='center',

                # Tamanho da fonte
                fontsize=8
            )

        # Define limite máximo do eixo X
        plt.xlim(0, media_por_estado.max() + 30)

        # Adiciona linhas de grade no eixo X
        plt.grid(axis='x', linestyle='--', alpha=0.5)

        # Ajusta automaticamente os elementos do gráfico
        plt.tight_layout()

        # Salva o gráfico em arquivo PNG
        plt.savefig(f'grafico_{ano}.png', dpi=300)

        # Fecha o gráfico para liberar memória
        plt.close()

        # Exibe mensagem de sucesso
        print(f'Gráfico {ano} salvo com sucesso.')

    # Caso o arquivo não seja encontrado
    except FileNotFoundError:

        # Exibe mensagem de erro
        print(f'Arquivo {arquivo} não encontrado.')